### ISSUE TITLE
[Feature Suggestion] Self-maintaining CFF

### ISSUE THREAD

**Issue by kevinmatthes** [sorairolake/sysexits-rs#14]
Happy New Year, @sorairolake!

During the past month, I developed a GitHub Action to make the CITATION.cff completely self-maintaining -- together with bump2version's tracking.  Previously, one had to adjust the release date by hand.  With the new Action, the release date will be set to the present day (or whatever the executing runner thinks the present day is) after bump2version incremented the version numbers.

There are in fact two editions:

* https://github.com/kevinmatthes/cff-release-today
* https://github.com/kevinmatthes/release-bump2version-scriv

The difference between those two is that the latter incorporates the former and also takes care of the version number increment -- as well as the CHANGELOG assembly.  There is no need to install additional software as the Actions take of them, if required.

The CHANGELOG assembly employs a Python 3 CLI named Scriv.  This Apache-2.0 software compiles the CHANGELOG from fragments stored in a dedicated directory of the repository.  These fragments contain the changes made to the project by a single branch.  Each contributor needs to add a Scriv fragment to the storage such that on release, Scriv can assemble the CHANGELOG from the fragments in the storage which is thereby cleared.  This procedure avoids frustration due to repetitive merge conflicts caused by CHANGELOG edits.  The supported CHANGELOG file formats are Markdown and ReStructuredText (RST), defaulting to the latter.

The idea behind both Actions is to create a release workflow (GitHub Action workflow) with manual trigger to delegate all release preparations to a GitHub Runner which finally commits them.  This reduces the required effort for a new release and saves, thus, precious development time.

I would like to ask whether you are interested in one of these Actions and, if so, if I should prepare an initial workflow configuration.  Therefore, I would need to know if also Scriv shall be configured.

**Comment by sorairolake** [comment]
@kevinmatthes I think the current method isn't too troublesome. So, I'm not interested in these.
