### ISSUE TITLE
[enhancement] Extend `io::ErrorKind` conversion

### ISSUE THREAD

**Issue by TheAlgorythm** [sorairolake/sysexits-rs#51]
In nightly there are more errorkinds (rust-lang/rust#86442).
These could be used something like this:
```rs
ErrorKind::AlreadyExists
| ErrorKind::IsADirectory
| ErrorKind::ReadOnlyFilesystem
| ErrorKind::FilenameTooLong => Self::CantCreat,
```

I suggest this behind a feature flag, as it could now be enabled on nightly and later, when stabilised, on new rustc versions by the user of the crate.

**Comment by sorairolake** [comment]
To do this, I think `Cargo.toml` should be like this:

```toml
[features]
default = ["std"]
std = []
nightly = []
```
